import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ types }) {
  return (
    <>
      <Head>
        <title>MakeUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Makeup
        </h1>

        <div className={styles.grid}>
          <Link href='/face'>
            <a className={styles.face}>
              <Image
                src="/assets/images/brushes.png"
                width={370}
                height={248}
                alt="Brashes"
                title="Face"
              />
            </a>
          </Link>
          <Link href='/brows'>
            <a className={styles.brows}>
              <Image
                src="/assets/images/powder.png"
                width={370}
                height={248}
                alt="Single pot"
                title="Brows"
              />
            </a>
          </Link>
          <Link href='/lips'>
            <a className={styles.lips}>
              <Image
                src="/assets/images/lips.png"
                width={370}
                height={510}
                alt="Lips"
                title="Lips"
              />
            </a>
          </Link>
          <Link href='/nails'>
            <a className={styles.nails}>
              <Image
                src="/assets/images/nailpolish.png"
                width={370}
                height={248}
                alt="Nail polish"
                title="Nails"
              />
            </a>
          </Link>
          <Link href='/eyes'>
            <a className={styles.eyes}>
              <Image
                src="/assets/images/eyeshadow.png"
                width={370}
                height={248}
                alt="Eyeshadow"
                title="Eyes"
              />
            </a>
          </Link>
        </div>
        <div>
          {types.map(type => (
            <Link href={`/category/${type}`} key={type}>
            <a className={styles.link}> {type.replace(/_/g, ' ')} </a>
          </Link>
          ))}
        </div>
      </main>
      <footer className={styles.footer}>

      </footer>
    </>
  )
}

export const getStaticProps = async() => {
  const res = await fetch(`http://makeup-api.herokuapp.com/api/v1/products.json`);
  const products = await res.json();
 
  const types = Array.from(new Set(products.map(product => (product.product_type))));

  return {
    props: {
      types,
    },
  }
}
